all:: advanced greeter mathservice task-api

.PHONY: advanced
advanced:
	cd advanced && make

.PHONY: greeter
greeter:
	cd greeter && make

.PHONY: mathservice
mathservice:
	cd mathservice && make

.PHONY: task-api
task-api:
	cd task-api && make